name: map_slide_puzzle
description: A Very Good Modification of a very_good_slide_puzzle (from Very Good Ventures).
version: 1.0.0+1
repository: https://github.com/tsinis/slide_puzzle
issue_tracker: https://github.com/tsinis/slide_puzzle/issues
maintainer: Roman Cinis
publish_to: none

environment:
  sdk: ">=2.17.0"
  flutter: ">=3.0.1"

dependencies:
  bloc: ^8.0.3
  confetti: ^0.7.0
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^1.1.0
  font_awesome_flutter: ^10.1.0
  gap: ^2.0.0
  google_fonts: ^3.0.1
  intl: ^0.17.0
  just_audio: ^0.9.21
  just_audio_libwinmedia:
    git:
      url: https://github.com/bdlukaa/just_audio_libwinmedia
      ref: e4882cec24cfdfe0931e7794ac7d46ad6b4d1804
  universal_platform: ^1.0.0+1
  url_launcher: ^6.1.2
  url_strategy: ^0.2.0
  websafe_svg: ^2.1.1
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding
      path: plugins/window_size
      ref: 5c51870ced62a00e809ba4b81a846a052d241c9f

dev_dependencies:
  bloc_test: ^9.0.3
  dart_code_metrics: ^4.15.2
  fake_async: ^1.3.0
  flutter_lints: ^2.0.1
  flutter_native_splash: ^2.2.1
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/audio/
    - assets/vectors/
  fonts:
    - family: GoogleSans
      fonts:
        - asset: assets/fonts/GoogleSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/GoogleSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/GoogleSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/GoogleSans-Italic.ttf
          weight: 400
          style: italic
