name: Deploy

on:
  push:
    paths:
      - "lib/**"
      - "pubspec.yaml"
      - "pubspec.lock"
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checks-out repository
      uses: actions/checkout@v2

    - name: Install Flutter
      uses: subosito/flutter-action@v2

    - name: Install Dependencies
      run: flutter pub get

    - name: Generate L10N
      run: flutter gen-l10n

    - name: Build for Web
      run: flutter build web --release

    - name: Deploy
      uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        repoToken: "${{ secrets.GITHUB_TOKEN }}"
        firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_MAP_SLIDE_PUZZLE }}"
        projectId: map-slide-puzzle
        channelId: live
        expires: 30d