name: Tests

on:
  push:
    paths:
      - "lib/**"
      - "test/**"
      - "pubspec.yaml"
      - ".github/workflows/tests.yaml"
  pull_request:
    paths:
      - "lib/**"
      - "test/**"
      - "pubspec.yaml"

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: Checks-out repository
      uses: actions/checkout@v3

    - name: Install Flutter
      uses: subosito/flutter-action@v2

    - name: Install app dependencies
      run: flutter pub get

    - name: Generate localization files
      run: flutter gen-l10n

    - name: Analyze
      run: flutter analyze lib test

    - name: Run tests
      run: flutter test --no-pub --coverage --test-randomize-ordering-seed random

    - name: Check Code Coverage
      uses: VeryGoodOpenSource/very_good_coverage@v1.2.1
      with:
        min_coverage: 95

    - name: Upload Code Coverage
      uses: codecov/codecov-action@v2
      with:
        file: ./coverage/lcov.info